server:
  port: 8075
  servlet:
    context-path: /flowable-master
spring:
  application:
    name: flowable-master
  datasource:
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:p6spy:mysql://127.0.0.1:3306/test_flowable?serverTimezone=UTC&characterEncoding=UTF8
    url: jdbc:mysql://127.0.0.1:3306/test_flowable?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456
  redis:
    database: 0
    #host: 192.168.100.31
    host: 192.168.100.43
    post: 6379
    password:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: mongodb-test

mybatis:
  mapper-locations: classpath*:com/flowable/springboot/mapper/*.xml

#配置的请求路径ip
task_url: http://fbpm-process/fbpm-process   #http://localhost:8079/fbpm-process

#启用 flowable 端点
management:
  endpoint:
    flowable:
      enabled: false